### PR TITLE
Improve tooling

### LINKED ISSUE #16: Outdated dependencies and broken build config
image

Dependencies are severely out of date. **I've manually checked through the newer major versions of each dep and they can be upgraded without any further change as they don't break anything we care about.** With the dependencies out of date, these errors occur:
image

Additionally, `@webosose/ares-cli` is only intended for use with the open source version of webos and not LG TV's version since it's missing ares-novacom, as [the employee on the LG developer forums can attest to that](https://developer.lge.com/community/forums/RetrieveForumContent.dev?detailContsId=FC17165606&sMenuId=53&contsTypeCode=QUE&prodTypeCode=TV#none). Additionally, `@webosose/ares-cli` causes npm to spew a lot of audit errors when installing so **I recommend removing this package as this can cause real audit problems to be missed.**

For the webpack config, using `es5` for targets will cause this error:
image
**I recommend moving the target in `babel.config.json` to a separate browserslist file and set `target: 'browserslist'` in webpack's config instead.**

### PR DESCRIPTION
**Pull request by fire332**
Check the first commit to see the actual changes.

- Added vscode, prettier, and eslint configs.
- Fixed eslint errors in the code.
- Updated `package-lock.json` to new lock file version.
- Made the `deploy` script multi OS compatible.
- Improved production bundle size. 174 KiB `userScript.js` + 922 B `index.js` -> 137 KiB `userScript.js` + 10.7 KiB `index.js`.
- Added pre-commit prettify hook.
- Polyfill `index.js`.
- ~Switched the `spatial-navigation-polyfill` to an NPM dependency.~

Closes #16

### CODE REVIEW

**Comment by fire332** [comment]
I just remembered, the domrect polyfill is also unnecessary if we check for and use `ClientRect` instead as appropriate. However, this needs testing to be sure. Obviously I can't test this as I own a LG C1 which uses Chromium 79.
image

**Comment by fire332** [comment]
Whoops. `@babel/runtime-corejs3` shouldn't be a dev dependency. Fixing now.

**Comment by Informatic** [comment]
DomRect is used by spatial navigation polyfill.

Additionally - spatnav polyfill was pulled into out repo specifically
becaused it had a bunch of patches to make it work properly on older
browsers. (I don't remember the specifics and am slightly AFK for the next
12+ hours, but all the changes had comments marked like here:
https://github.com/webosbrew/youtube-webos/blob/main/src/spatial-navigation-polyfill.js#L673
)

**Comment by fire332** [comment]
Ah ok, just saw your comment. You may want to make the changes more obvious as I couldn't tell from a quick glance. Reverting that portion now.

**Comment by Informatic** [comment]
Hey, sorry for the delay.

Can you please check if SponsorBlock segments are properly rendered on the timeline on Your TV? I can consistently make them work on current `main` (on [this video](https://www.youtube.com/watch?v=ptnXLYYIQ9Y)), but can't on this branch. No obviois

Oneliner:
```sh
git stash && git checkout main && npm install && npm run build && npm run package && npm run deploy && npm run launch -- -p '{"contentTarget":"v=ptnXLYYIQ9Y"}'
```

I see an `undefined is not a function` error occuring on this line:
https://github.com/webosbrew/youtube-webos/blob/06b8bc91e193cbadaa537d0b7cdc1b8694adab42/src/sponsorblock.js#L171

Indeed - on `main` `NodeList.prototype.forEach` is a properly shimmed native function, while it doesn't seem to be shimmed in this branch.

**Comment by fire332** [comment]
Is that specific instance of `NodeList` missing the `.forEach` or is `.forEach` missing on the global `NodeList`'s prototype?

**Comment by Informatic** [comment]
That's on global `NodeList` prototype (`NodeList.prototype.forEach` I mentioned)

**Comment by fire332** [comment]
Can you check to see if this works?

**Comment by Informatic** [comment]
Tested on 9637280824fc54c1e6985f01f4622b3877e523b3, sadly, still doesn't work :/

`NodeList.prototype.forEach` is still `undefined`, and the same `Uncaught TypeError: undefined is not a function` still occurs.

**Comment by fire332** [comment]
Try again with polyfill-corejs3's method set to `'usage-global'` instead of `'usage-pure'`.

image

**Comment by Informatic** [comment]
Ah, indeed. Now with `usage-global` and `core-js-pure` dependency replaced with `core-js` (otherwise it'd fail on missing `core-js` with that previous option changed) it works correctly now it seems. I'll do deeper testing in a couple of hours, but looks great so far. Thank you.

**Comment by fire332** [comment]
Talked to the core-js dev. Seems like a Babel bug that `NodeList.prototype.forEach` is not pollyfilled in pure mode and looking at the Babel issue tracker, doesn't seem like this will be fixed any time soon. Better if we just migrate all usage of `.forEach` on `NodeList`s to use `for...of` syntax instead.

**Comment by fire332** [comment]
Please test the follow commit. I'll rebase them all if this is good.

**Comment by Informatic** [comment]
Works perfectly now. Thanks.

**Comment by fire332** [comment]
Please don't merge before I get around to rebasing, unless you truly don't mind having commits labeled `test` and `test2` in the repository.

**Comment by Informatic** [comment]
Sure, though squashing would probably work just fine in our case. (GitHub
is able to do that automatically right before merge)

**Comment by fire332** [comment]
I recommend having a separate commit just for the `prettify` command as it touches almost every file, making the actual changes a pain to diff. Rebasing done. Good to merge.

**Comment by Informatic** [comment]
Yeah that makes sense. I suspect you're going to need to rebase other PRs as well after we merge it in.

**Pull request merged**
