### PR TITLE
More performant YouTube Logo hide option.

### PR DESCRIPTION
**Pull request by tomikaka22**
This pull request adds an option to hide the YouTube logo from the top right corner of the app.

Me and the creator of [youtube-webos-cobalt](https://github.com/GuillaumeSmaha/youtube-webos-cobalt-app) modified the code of #56 a while ago to work without the deprecated [DOMNodeInserted](https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent) event, thus making it more performant and up to date.

### CODE REVIEW

**Comment by fire332** [comment]
Is it possible to just inject a stylesheet that hides the CSS class instead of re-applying the style change every X seconds? Does YouTube allow 'unsafe-inline' for style tags in its CSP header?

**Comment by tomikaka22** [comment]
I don't think I'm applying anything X seconds unless I'm missing something.

**Comment by fire332** [comment]
Apologies. I've misinterpreted the code in my haste. Regardless, my question still stands out of curiosity at the very least.

**Comment by tomikaka22** [comment]
It'd probably be possible, but I think making the logo container opaque directly in the JavaScript is the simplest.

Unless there is already a mechanism that loads stylesheets based on config options.

**Comment by throwaway96** [comment]
Is it really necessary to call `logoHideShow()` three times?

**Comment by fire332** [comment]
We already achieve the same goal of waiting for an element to be added before doing something to it [here](https://github.com/webosbrew/youtube-webos/blob/9ac14a76ab13d7478d3a4ae49cb5c35e1cf1c54d/src/userScript.js#L22).

**Comment by throwaway96** [comment]
> We already achieve the same goal of waiting for an element to be added before doing something to it [here](https://github.com/webosbrew/youtube-webos/blob/9ac14a76ab13d7478d3a4ae49cb5c35e1cf1c54d/src/userScript.js#L22).

That makes a lot more sense to me. Why does it look at attributes though?

**Comment by throwaway96** [comment]
This works for me.
```js
async function logoHideShow() {
  const logo = await waitForChildAdd(
    document.getElementById('container'),
    (node) => node.nodeName === 'YTLR-REDUX-CONNECT-YTLR-LOGO-ENTITY'
  );

  logo.style.opacity = configRead('hideLogo') ? '0' : '1';
}
logoHideShow();
```

I also disabled the attribute stuff in `waitForChildAdd()`, and it still finds the video and logo elements. It doesn't appear to be necessary for current uses of `waitForChildAdd()`. Is there a rationale for leaving it in?

**Comment by fire332** [comment]
If the Mutation Observer doesn't fire on attribute change, one must carefully craft the predicate to only rely on properties that exist when the node is added.

It's not worth trading the principle of least surprise for a handful of milliseconds faster startup.

**Comment by throwaway96** [comment]
The name and description of `waitForChildAdd()` imply to me that the checks will be made when a child is added, not later on when its attributes are modified.

In the single existing use of `waitForChildAdd()` and this new one, the tests (which are both fairly intuitive) work fine without attributes, so it doesn't seem like predicates have to be that carefully crafted.

I might feel differently if anyone were actually using the attribute functionality. If it's not removed, it should at least be made optional. I'm not sure whether it should be enabled by default though.

**Comment by throwaway96** [comment]
> Does YouTube allow 'unsafe-inline' for style tags in its CSP header?

I'm not actually seeing a `Content-Security-Policy` header (or `<meta http-equiv>`), but it looks like all `<style>` elements have a `nonce` attribute. Still, I just tested injecting `<style>` without `nonce` (on webOS 6.3.2), and it worked.

The [version I'm currently using](https://github.com/webosbrew/youtube-webos/blob/6cd3bbe039720bdb3b80bd12bc6e3ddcc1c1c806/src/ui.js#L216-L229) is based on `waitForChildAdd()`—which I only learned of yesterday. If someone wants to write a version that injects a stylesheet, please let me know (otherwise I may look into doing it myself). I think we should probably be avoiding `setTimeout()`/`setInterval()` unless they're truly necessary.

**Comment by fire332** [comment]
In a perfect world, we would do this:
```css
body:has(#__hide_logo:checked) .ytlr-redux-connect-ytlr-logo-entity {
  visibility: hidden !important;
}
```
Which would mean we wouldn't need JS at all for this functionality.

But too bad we're not in a perfect world because [`:has` is only supported in Chrome 105+](https://caniuse.com/css-has) and the polyfill looks expensive.

# Method 1: toggle entire stylesheet
Create a new CSS file:
`./hide-ytlogo.css`
```css
.ytlr-redux-connect-ytlr-logo-entity {
  visibility: hidden !important;
}
```
And use it like so:
```js
const ele = document.createElement('link')
ele.rel = 'stylesheet'
// URL asset: https://webpack.js.org/guides/asset-modules/#url-assets
ele.href = new URL('./hide-ytlogo.css', import.meta.url)
document.head.appendChild(ele)

// `disabled` is available on `link[rel="stylesheet"]`
// See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#disabled
ele.disabled = !configRead('hideLogo')
```

# Method 2: toggle class on body
`./hide-ytlogo.css`
```css
body.logo-hidden .ytlr-redux-connect-ytlr-logo-entity {
  visibility: hidden !important;
}
```
```js
import './hide-ytlogo.css'
if (configRead('hideLogo'))
  document.body.classList.add('logo-hidden')
else
  document.body.classList.remove('logo-hidden')

**Comment by throwaway96** [comment]
I don't think a separate CSS file is necessary. This seems to work in my testing:
```js
/**
 * Initialize ability to hide YouTube logo in top right corner.
 */
function initHideLogo() {
  const style = document.createElement('style');
  document.head.appendChild(style);

  /** @type {(hide: boolean) => void} */
  const setHide = (hide) => {
    const opacity = hide ? '0' : '1';
    style.textContent = `ytlr-redux-connect-ytlr-logo-entity { opacity: ${opacity}; }`;
  };

  setHide(configRead('hideLogo'));

  configAddChangeListener('hideLogo', (evt) => {
    setHide(evt.detail.newValue);
  });
}
```

**Comment by fire332** [comment]
That also works too. Though visibility should be used instead of opacity so the element isn't interactable.

**Comment by throwaway96** [comment]
Any objections to closing this in favor of #149?

**Comment by tomikaka22** [comment]
Looks good to me, happy to see this feature finally making it after all this time.

**Pull request closed without merging**
