### PR TITLE
appinfo: add deeplinking/voicesearch options

### LINKED ISSUE #1: voice search
voice search does not work
opening links does not work during voice search in the system, it just opens the application

webos 5+

the best application for bypassing ads, unfortunately for all 5+ webos users it is of little use without these functions

### PR DESCRIPTION
**Pull request by Informatic**
Fixes #1 , FriedChickenButt/youtube-webos#29.

Verified on webOS 3.8 with voice search. Also fixes in-app voice search on webOS 5.x as reported on Discord directly.

We also add an unknown option that possibly fixes FriedChickenButt/youtube-webos#25

### CODE REVIEW

**Comment by fire332** [comment]
Does not work for videos directly from home deck on webOS 6. Seems like prepending `v=` is redundant.
image

**Comment by Informatic** [comment]
[youtube.leanback.v4_0.1.1_all.zip](https://github.com/webosbrew/youtube-webos/files/7712456/youtube.leanback.v4_0.1.1_all.zip)
Try this one out please.

**Comment by Informatic** [comment]
[youtube.leanback.v4_0.1.1_all-contentTarget.zip](https://github.com/webosbrew/youtube-webos/files/7712486/youtube.leanback.v4_0.1.1_all-contentTarget.zip)
also possibly this one too - I've reverted a change that caused breakage on some versions, but increased startup/relaunch time on some other versions...

**Comment by Informatic** [comment]
This is all very webOS version dependent. On webOS 5.x `$CONTENTID` does indeed contain `v=`, while on webOS 4.x and 3.x it does not. I think it should be fairly safe this way...

The question now is whether or not any/both of these versions work for you properly now?

**Comment by fire332** [comment]
Both of them don't work.

image
image

**Comment by Informatic** [comment]
Ah yeah, that's my bad. :/ This is what I get for rolling out a test release without testing. Sorry.
[youtube.leanback.v4_0.1.1_all-contentTarget2.zip](https://github.com/webosbrew/youtube-webos/files/7740513/youtube.leanback.v4_0.1.1_all-contentTarget2.zip)

**Comment by BDvirus** [comment]
Thank you!! it's working :) 
Tested with webos 6 (03.20.80)

**Comment by Informatic** [comment]
Merging in then.

**Comment by Informatic** [comment]
Dammit.

**Pull request merged**
