### PR TITLE
Added adblock for "autoplay" ad tile on home screen

### PR DESCRIPTION
**Pull request by pvrs12**
YouTube "recently" added a tile which is automatically selected and will autoplay an ad on launch. This removes that tile

image_720

### CODE REVIEW

**Comment by throwaway96** [comment]
How have you tested this, and on what platform(s): webOS version, firmware version, SoC, etc.? The changes to files other than `src/adblock.js` will have to be removed before this can be merged.

**Comment by jospezial** [comment]
Looks like duplicate of https://github.com/webosbrew/youtube-webos/pull/100
that was merged.

**Comment by jospezial** [comment]
@pvrs12 Does your code still remove that tile always?
Merged Commit from #100 has problems blocking the tile now.

**Comment by pvrs12** [comment]
I'll have to re-test. I didn't have a great dev setup when I first wrote that. I'll try to test sometime this week

**Pull request closed without merging**
